### ISSUE TITLE
New Classification bugs

### ISSUE THREAD

**Issue by sangloo** [Togal-ai-Team/eslint-config-togal#28]

**Comment by JenniferNassar** [comment]
https://www.loom.com/share/f0bfa723ed1b40ceb4645ae0284b2691 : I rename the "net area" as "area 1" and label some polygons "area 1", when I go back to the project page and open the drawing one more time the polygon named "area 1" turned "net area"

**Comment by JenniferNassar** [comment]
https://www.loom.com/share/a90e37fdde624be28e500e8ff48ba986 : when I create  and name  new org level classification I can't add a label in it

**Comment by yuliiabilan** [comment]
number of drawings uploaded to the set  is not updating immediately unless manual page refresh or exiting the project
https://togal-ai.slack.com/files/U0399AACNC9/F03D5R9RZEJ/number_of_drawings_in_set.mp4

**Comment by JenniferNassar** [comment]
https://www.loom.com/share/60c140df01964166b72eeebe81ae2ffd: When I hit capslock and search for the drawings, it doesn't work

**Comment by JenniferNassar** [comment]
https://www.loom.com/share/ba560c63676a4884abca341244caa790 : not able to delete an empty folder

**Comment by JenniferNassar** [comment]
https://www.loom.com/share/744cf565a7774b95bfe3c3a6bad7aba1 :
1- there are 2 polygons that do not appear in the qty panel
2- I can't hide the legend tool in the qty panel, I should hold "alt" and hide all of the classifications

**Comment by JenniferNassar** [comment]
https://www.loom.com/share/25ad2f1a31044e6bab1cde3e222936ea: can't auto classify and click the first option in the list because of hovering over the rest groups

**Comment by cpettibone** [comment]
In the central classification settings https://www-staging.togal.ai/dashboard/settings you can add a Group but you can't add any classifications inside the group. 
Here's how it is on Production:
![add classification inside group production.png](https://images.zenhubusercontent.com/618ea88b279f67f605afd309/3ca13973-f455-4adf-b81e-f87389a59cc0)
On Staging (and clicking Add does nothing ... and it should say Add Classification like it used to)
![add classification inside group staging.png](https://images.zenhubusercontent.com/618ea88b279f67f605afd309/f061f6f7-a7bf-47ce-8cf9-3f12f8c38ca5)

**Comment by cpettibone** [comment]
New Org level classifications don't show up in the Library. I set these here:
![Org Classifications.png](https://images.zenhubusercontent.com/618ea88b279f67f605afd309/3b91633f-d145-4c08-8449-d3cf5ca7cab7)

Only the group names display in the Library, but the classification do not:
![new classifications not in Library panel.png](https://images.zenhubusercontent.com/618ea88b279f67f605afd309/4b6aec70-ed79-4a4d-9d60-d03bc50a5d61)

**Comment by cpettibone** [comment]
Creating a new classification from quantity panel doesn't add it to quantity panel

**Comment by shoniko** [comment]
Ready to test

**Comment by yuliiabilan** [comment]
1. 'not able to import classifications from another set' - worked on staging before the Library is back, now with Library logic is different
2. renaming net area - another issue detected and reported separately - [1145](https://app.zenhub.com/workspaces/togal-60abe0f8d5364e00181f4762/issues/togal-ai-team/frontend/1145)
3. new org level class - works
4.  number of drawing in the set not updating - still reproducible , reported separately - [1146](https://app.zenhub.com/workspaces/togal-60abe0f8d5364e00181f4762/issues/togal-ai-team/frontend/1146)
5. capslock/upper case + lock - works
6. delete empty folder - works
7. can't hide the legend - works
8. 'can't auto classify and click the first option in the list because of hovering over the rest groups ' - works OK, in a different way now
9. Add Classification + Edit/Delete - works
10.  adding classification form quantity panel - works
